# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(981, 627)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(981, 627))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.rit_logo = QtGui.QLabel(self.centralwidget)
        self.rit_logo.setGeometry(QtCore.QRect(360, -20, 250, 111))
        self.rit_logo.setObjectName(_fromUtf8("rit_logo"))
        self.project_title = QtGui.QLabel(self.centralwidget)
        self.project_title.setGeometry(QtCore.QRect(330, 110, 303, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Manjari"))
        self.project_title.setFont(font)
        self.project_title.setObjectName(_fromUtf8("project_title"))
        self.dsp = QtGui.QCheckBox(self.centralwidget)
        self.dsp.setGeometry(QtCore.QRect(32, 514, 168, 41))
        self.dsp.setChecked(True)
        self.dsp.setObjectName(_fromUtf8("dsp"))
        self.reset_button = QtGui.QPushButton(self.centralwidget)
        self.reset_button.setEnabled(True)
        self.reset_button.setGeometry(QtCore.QRect(212, 510, 141, 41))
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName(_fromUtf8("reset_button"))
        self.listView_2 = QtGui.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(532, 160, 441, 411))
        self.listView_2.setMouseTracking(False)
        self.listView_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.listView_2.setObjectName(_fromUtf8("listView_2"))
        self.syn_button = QtGui.QPushButton(self.centralwidget)
        self.syn_button.setGeometry(QtCore.QRect(370, 510, 141, 41))
        self.syn_button.setDefault(True)
        self.syn_button.setObjectName(_fromUtf8("syn_button"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(672, 170, 172, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.kan_input = QtGui.QTextEdit(self.centralwidget)
        self.kan_input.setGeometry(QtCore.QRect(29, 170, 481, 75))
        self.kan_input.setFrameShadow(QtGui.QFrame.Plain)
        self.kan_input.setObjectName(_fromUtf8("kan_input"))
        self.columnView_2 = QtGui.QColumnView(self.centralwidget)
        self.columnView_2.setGeometry(QtCore.QRect(10, 160, 511, 411))
        self.columnView_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.columnView_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.columnView_2.setObjectName(_fromUtf8("columnView_2"))
        self.recent_table = QtGui.QTableWidget(self.centralwidget)
        self.recent_table.setGeometry(QtCore.QRect(540, 190, 419, 371))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recent_table.sizePolicy().hasHeightForWidth())
        self.recent_table.setSizePolicy(sizePolicy)
        self.recent_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.recent_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.recent_table.setGridStyle(QtCore.Qt.DotLine)
        self.recent_table.setObjectName(_fromUtf8("recent_table"))
        self.recent_table.setColumnCount(4)
        self.recent_table.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.recent_table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.recent_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.recent_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.recent_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.recent_table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.recent_table.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.recent_table.setItem(0, 3, item)
        self.recent_table.horizontalHeader().setVisible(True)
        self.recent_table.horizontalHeader().setHighlightSections(False)
        self.recent_table.verticalHeader().setDefaultSectionSize(40)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 250, 93, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 140, 961, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(517, 160, 20, 411))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.en_input = QtGui.QTextEdit(self.centralwidget)
        self.en_input.setGeometry(QtCore.QRect(30, 310, 481, 75))
        self.en_input.setFrameShadow(QtGui.QFrame.Plain)
        self.en_input.setObjectName(_fromUtf8("en_input"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 390, 93, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.translate_button = QtGui.QPushButton(self.centralwidget)
        self.translate_button.setGeometry(QtCore.QRect(370, 390, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.translate_button.setFont(font)
        self.translate_button.setObjectName(_fromUtf8("translate_button"))
        self.columnView_2.raise_()
        self.listView_2.raise_()
        self.rit_logo.raise_()
        self.project_title.raise_()
        self.dsp.raise_()
        self.reset_button.raise_()
        self.syn_button.raise_()
        self.label_6.raise_()
        self.kan_input.raise_()
        self.recent_table.raise_()
        self.label_7.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.en_input.raise_()
        self.label_8.raise_()
        self.translate_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuLicense = QtGui.QMenu(self.menubar)
        self.menuLicense.setObjectName(_fromUtf8("menuLicense"))
        self.menuSource_Code = QtGui.QMenu(self.menubar)
        self.menuSource_Code.setObjectName(_fromUtf8("menuSource_Code"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionDevelopers = QtGui.QAction(MainWindow)
        self.actionDevelopers.setObjectName(_fromUtf8("actionDevelopers"))
        self.actionMentor = QtGui.QAction(MainWindow)
        self.actionMentor.setObjectName(_fromUtf8("actionMentor"))
        self.actionAbout_Project = QtGui.QAction(MainWindow)
        self.actionAbout_Project.setObjectName(_fromUtf8("actionAbout_Project"))
        self.actionPython_Source = QtGui.QAction(MainWindow)
        self.actionPython_Source.setObjectName(_fromUtf8("actionPython_Source"))
        self.actionUI_Source = QtGui.QAction(MainWindow)
        self.actionUI_Source.setObjectName(_fromUtf8("actionUI_Source"))
        self.menuAbout.addAction(self.actionDevelopers)
        self.menuAbout.addAction(self.actionMentor)
        self.menuAbout.addAction(self.actionAbout_Project)
        self.menuSource_Code.addAction(self.actionPython_Source)
        self.menuSource_Code.addAction(self.actionUI_Source)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuLicense.menuAction())
        self.menubar.addAction(self.menuSource_Code.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Kannada Speech Synthesis", None))
        self.rit_logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/RIT_logo/img/rit_logo.png\" height=\"125\" width=\"250\"/></p></body></html>", None))
        self.project_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#55557f;\">Kannada Speech Synthesis</span></p></body></html>", None))
        self.dsp.setText(_translate("MainWindow", "Apply DSP Operation", None))
        self.reset_button.setText(_translate("MainWindow", "Clear", None))
        self.syn_button.setText(_translate("MainWindow", "Synthesize", None))
        self.label_6.setText(_translate("MainWindow", "Recent Synthesis Results", None))
        self.recent_table.setSortingEnabled(False)
        item = self.recent_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.recent_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Play Audio", None))
        item = self.recent_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kannada Text", None))
        item = self.recent_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DSP", None))
        item = self.recent_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "User Rating", None))
        __sortingEnabled = self.recent_table.isSortingEnabled()
        self.recent_table.setSortingEnabled(False)
        self.recent_table.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Kannada Text", None))
        self.label_8.setText(_translate("MainWindow", "English Text", None))
        self.translate_button.setText(_translate("MainWindow", "Translate", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.menuLicense.setTitle(_translate("MainWindow", "License", None))
        self.menuSource_Code.setTitle(_translate("MainWindow", "Source Code", None))
        self.actionDevelopers.setText(_translate("MainWindow", "Developers", None))
        self.actionMentor.setText(_translate("MainWindow", "Mentor", None))
        self.actionAbout_Project.setText(_translate("MainWindow", "About Project", None))
        self.actionPython_Source.setText(_translate("MainWindow", "Python Source", None))
        self.actionUI_Source.setText(_translate("MainWindow", "UI Source", None))

import AppResources
